# ------------------------------------------------------------------------------
# create-site.yml
# ------------------------------------------------------------------------------

---

- hosts: prod4

  tasks:

    - ansible.builtin.import_role:
        name: wordpress_apache
        tasks_from: create-sites
      tags: wordpress
